### ISSUE TITLE
Installation failed due to dependencies

### ISSUE THREAD

**Issue by bnorthoff** [marcelm/xopen#10]
I using Python 3.6.5, pip 19.0.3, SLE 15 and wanted to install xopen (used for cutadapt) using Python3. Installation was performed adding a proxy: sudo pip3 install xopen –proxy address.of.my.proxy.com:8080.
Setuptools (setuptools-40.8.0), setuptools_scm (3.2.0) and wheel (0.33.1) were already installed. However I have some troubles with the dependencies and network connectivity:

Collecting xopen
  Using cached https://files.pythonhosted.org/packages/c4/3b/52f8a5d32c97e6301ea85419f0fc0eaed5cfaedc6a973990a2908116da31/xopen-0.5.0.tar.gz
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3 /usr/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-a9co28rs/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel setuptools_scm:
  Collecting setuptools
    Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2637ec2198>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',)': /simple/setuptools/
    Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2637ec2208>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',)': /simple/setuptools/
    Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2637ea44e0>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',)': /simple/setuptools/
    Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2637ea4588>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',)': /simple/setuptools/
    Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2637ea4908>: Failed to establish a new connection: [Errno 101] Das Netzwerk ist nicht erreichbar',)': /simple/setuptools/
    Could not find a version that satisfies the requirement setuptools (from versions: )
  No matching distribution found for setuptools

  ----------------------------------------
Command "/usr/bin/python3 /usr/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-a9co28rs/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel setuptools_scm" failed with error code 1 in None

**Comment by marcelm** [comment]
This doesn’t look like something I can do much about. I would guess that this is a bug in pip.

Ok, after some searching I found pypa/pip#6018 which I would guess is the problem here: When pip installs build dependencies (such as `setuptools_scm`), it does not use the configured proxy settings.

For the time being, you could try the workaround given in the bug report:
> Disabling build isolation with --no-build-isolation and manually installing the build requirements first lets you work around this issue.

Since you say that `setuptools_scm` was already installed, you should only need to add `--no-build-isolation`.

**Comment by bnorthoff** [comment]
Downlaoding and installing xopen manually using setup.py solved the problem.

**Comment by marcelm** [comment]
Alright, thanks for letting me know. Let’s hope the pip bug gets fixed as well.
