### ISSUE TITLE
Should PipedGzipWriter implement __iter__?

### ISSUE THREAD

**Issue by kyleabeauchamp** [marcelm/xopen#12]
I was hoping to use xopen to handle writing a gzipped CSV, via pandas.  I ended up getting an exception:

```
import xopen
import pandas as pd

df = pd.DataFrame(dict(A=[1,2,3], B=[2,3,4], C=[1,1,1]))

with xopen.xopen("test.gz", mode='w') as fh:
    df.to_csv(fh)

ValueError: Invalid file path or buffer object type: <class 'xopen.PipedGzipWriter'>
```

Looking more carefully, this exception is triggered because the `PipedGzipWriter` doesn't have an `__iter__` member function: 
https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/inference.py#L186

Do you think this is a bug on the pandas side or the xopen side?  It's unclear to me whether the writer ought to have an iter object per the file spec.  What do you think?

**Comment by marcelm** [comment]
Hm, I don’t get why a file-like object that is used for writing should be iterable, but I guess I could just emulate the behaviour of the built-in classes:
```python
>>> f = open('new-file', 'w')
>>> next(iter(f))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
io.UnsupportedOperation: not readable
```

**Comment by marcelm** [comment]
Ok, I guess the `PipedGzipReader`/-`Writer` classes should actually inherit from [IOBase](https://docs.python.org/3/library/io.html#class-hierarchy) to be considered proper I/O classes. Let me see whether that is easy. If not, I’ll just add `__iter__` for now.

**Comment by marcelm** [comment]
I’ve searched for a while for how to do this properly, but IOBase is somewhat underdocumented. I’ve now just added `__iter__`. I’ll make a new release when we’re happy with PR #11.

**Comment by marcelm** [comment]
New release is out.
