### ISSUE TITLE
readline() function in PipedGzipReader

### ISSUE THREAD

**Issue by Martin1887** [marcelm/xopen#13]
Hello.

The `readline` function is not implemented in the `PipedGzipReader` class.

I think that implementing it is easy and it would be really useful. I think that implementation would be very similar to the `read` function:

```python
def readline(self, *args):
    data = self._file.readline(*args)
    if len(args) == 0 or args[0] <= 0:
        # wait for process to terminate until we check the exit code
        self.process.wait()
    self._raise_if_error()
    return data
```

Correct me if I'm wrong.

Thanks and Regards.

**Comment by marcelm** [comment]
Thanks for the suggestion! I’ve added this now exactly as you suggested, along with some unit tests. This will indeed be good to have.

If you want to contribute more and speed up getting your changes in, then you could also open a pull request. This makes it a bit easier to discuss code changes and I can just click "Merge" when I think the changes are ok.

Thanks again!
