### ISSUE TITLE
Move xopen to conda-forge

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/xopen#18]
The update of xopen on bioconda is flagged as: "move to conda-forge" which is fair. 
I have migrated a few packages to conda-forge already, and I really like to contribute back a bit to this nice project, so I created a new recipe on conda-forge for xopen [here](https://github.com/conda-forge/staged-recipes/pull/9154).
I added you as principal maintainer (the conda-forge bot does all the work, no need to worry!). But I need your explicit permission for that before this can be merged. If you don't like maintaining this on conda-forge, I will gladly do this for you.

**Comment by marcelm** [comment]
Thanks, very nice! Moving to conda-forge is the right thing to do. I’ve contributed to conda-forge before, so I’m familiar with the process. I’m happy to be listed as maintainer.

**Comment by marcelm** [comment]
I’ve also sent you an invite for push access to this repo. It would be great to have you as a co-maintainer here as well (increasing the bus factor, you know ...).

If you agree, it would be nice if you would open PRs for anything that is nontrivial just as before so we can discuss the changes.

**Comment by rhpvorderman** [comment]
I am delighted to be co-maintainer of this repo!

About the PR's: we do that in our insttitute all the time. Getting feedback is the best way to learn + it tends to make the software a lot better. So I won't abuse my push powers :wink:.

**Comment by marcelm** [comment]
Great, looking forward to this!

And I guess this issue can now be closed in favor of the PR on conda-forge.
