### ISSUE TITLE
Idea: support for file-type detection via magic numbers

### ISSUE THREAD

**Issue by winni2k** [marcelm/xopen#4]
I just came across this project, and I was wondering if there was any particular reason that the file type is being inferred from the file name ending instead of the file's [magic number](http://www.astro.keele.ac.uk/oldusers/rno/Computing/File_magic.html)?

**Comment by marcelm** [comment]
The main reason is that I started with name-based detection and it has worked well enough so far. Another reason is that named pipes aren’t seekable, which complicates the implementation if we want the content-based detection to work also for them.

**Comment by wkretzsch** [comment]
Fair enough. 

Aren't named pipes peek-able?

**Comment by marcelm** [comment]
This has now been implemented thanks to a contribution from @bvaisvil . I’m releasing version 0.9.0 at the moment, which includes this change.
