### ISSUE TITLE
`.read()`-ing gzipped file with no trailing newline results in no output

### ISSUE THREAD

**Issue by kristjaneerik** [marcelm/xopen#5]
Here's a snapshot + comments from an IPython session showing this bug:
```python
# let's make a file with a single line and a trailing newline
In [12]: f = xopen.xopen('test')
In [13]: f.read()
Out[13]: 'first line\n'   # as expected
In [14]: f.close()

# let's make a file with no trailing newline
In [15]: f = xopen.xopen('test', 'w')
In [16]: f.write('first line')
In [17]: f.close()
In [18]: f = xopen.xopen('test')
In [19]: f.read()
Out[19]: 'first line'  # as expected
In [20]: f.close()

# now, run `gzip test` to compress the no-newline file and open it for reading:
In [21]: f = xopen.xopen('test.gz')
In [22]: f.read()
# no output -- unexpected
In [23]: f.close()

# now let's open it again but read it using an iterator:
In [24]: f = xopen.xopen('../pdtk-dumps/test.gz')
In [25]: for line in f:
    ...:     print("'{}'".format(line))
    ...:
'first line'  # expected output!
In [26]: f.close()
```

Ran into this because `json.dump` was not writing a trailing newline.

Perhaps
```python
data = self._file.read(*args)
```
in `PipedGzipReader.read` should be replaced with something like:
```python
data = "".join(self)
```
I haven't put much thought into this, just wanted to leverage `PipedGzipReader.__iter__` which works correctly as the example above shows

**Comment by marcelm** [comment]
Oh, thanks for finding this! I can confirm that the problem is there, but only on Python 2. I’m looking into it.

**Comment by marcelm** [comment]
The `read()` function was simply missing a `return data` statement. The tests did not cover `PipedGzipReader.read()`, so this went unnoticed. (And I have always used `__iter__` so far.) Thanks again for catching this!

**Comment by kristjaneerik** [comment]
> The read() function was simply missing a return data statement.
Oops, I missed that hehe. Thanks for fixing!
